version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-publish:
    working_directory: ~/rn-signal-protocol-messaging
    docker:
      - image: circleci/node:10.14.0
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/rn-signal-protocol-messaging/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            .circleci/announcePublish.sh "Signal Protocol React Native module" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"
      - slack/status:
          fail_only: true
          failure_message: "Triggered by: *${CIRCLE_USERNAME}* \n\n Ooops! The *$CIRCLE_JOB* job has failed! :circleci-fail:"
          webhook: "${SLACK_STATUS_WEBHOOK}"

workflows:
  version: 2
  publish:
    jobs:
      - build-publish:
          filters:
            branches:
              only:
                  - master
