version: 2
jobs:
  build:
    working_directory: ~/rn-signal-protocol-messaging
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          name: Append circleCI build number to version
          command: |
            git config user.email "devops@pillar.io"
            git config user.name "Issabot"
            npm version $(node -e "const currentVersion=require('./package.json').version; const firstTwoDots=currentVersion.substring(0, currentVersion.lastIndexOf('.')+1); console.log(firstTwoDots);")$CIRCLE_BUILD_NUM
      - run:
            name: Authenticate with registry
            command: curl -u $ARTIFACTORY_PUBLISHING_USER:$ARTIFACTORY_PUBLISHING_PASSWORD https://pillarproject.jfrog.io/pillarproject/api/npm/auth >> ~/rn-signal-protocol-messaging/.npmrc
      - run:
          name: Publish Package to Artifactory
          command: npm publish --registry https://pillarproject.jfrog.io/pillarproject/api/npm/npm/
      - run:
          name: Announce Publish
          command: |
            chmod +x .circleci/announcePublish.sh
            .circleci/announcePublish.sh "Signal Protocol React Native module" "$(node -e "console.log(require('./package.json').name)")@$(node -e "console.log(require('./package.json').version)")"

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
